[package]
name = "cli"
version = "0.1.3"
edition = "2024"


[lints]
# workspace = true

[dependencies]
anyhow = "1.0.104"
chrono = { workspace = true, features = ["serde"] }
color-eyre = "0.6.5"
bincode-next = { workspace = true }
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures.workspace = true
ratatui = { version = "0.30.2", features = ["widget-calendar"] }
textwrap = "0.16.2"
tokio = { workspace = true, features = ["time"] }
webdav-server = { path = "../server" }
kosh-core = { path = "../core" }
qrcodegen = "1.8.0"
bip39 = "3.0.0"
base64 = "0.23.1"
local-ip-address = "0.6.13"
