use std::{
    io::{Cursor, Error},
    path::Path,
};

use crate::tls::Error::NoCertificatesFound;

use super::error::Result;
use rcgen::generate_simple_self_signed;
use rustls_pemfile::certs;
use sha2::{Digest, Sha256};
use tokio::{fs, io};

/// A loaded TLS identity consisting of a self-signed certificate and its private key,
/// both stored in PEM format.
///
/// The certificate is generated by [`rcgen`] and covers the Subject Alternative Names
/// `localhost`, `127.0.0.1`, and `0.0.0.0`, making it suitable for LAN deployments.
///
/// Use [`Identity::load_or_create`] at server startup to either load an existing identity
/// from disk or generate a fresh one. The resulting identity is then passed to the
/// [`crate::tls`] module and the admin CLI for TOFU device pairing.
pub struct Identity {
    /// The certificate in PEM format, including the `-----BEGIN CERTIFICATE-----` header.
    pub cert_pem: String,
    /// The private key in PEM format, including the `-----BEGIN PRIVATE KEY-----` header.
    pub key_pem: String,
}

impl Identity {
    /// Loads an existing TLS identity from `<vault_path>/tls/`, or generates a new one.
    ///
    /// If `cert.pem` and `key.pem` are both present under `<vault_path>/tls/`, they are
    /// read and returned as-is. If either file is missing, a fresh self-signed certificate
    /// is generated via [`rcgen`] and written to that directory.
    ///
    /// # Errors
    ///
    /// Returns [`super::Error::Io`] if the `tls/` directory cannot be created, or if the PEM
    /// files cannot be read or written. Returns [`super::Error::CertificateGen`] if `rcgen`
    /// fails to generate a valid certificate.
    pub async fn load_or_create<P>(vault_path: P) -> Result<Self>
    where
        P: AsRef<Path>,
    {
        let tls_dir = vault_path.as_ref().join("tls");
        let cert_path = tls_dir.join("cert.pem");
        let key_path = tls_dir.join("key.pem");

        if cert_path.exists() && key_path.exists() {
            Self::load(&cert_path, &key_path).await
        } else {
            fs::create_dir_all(tls_dir).await?;
            Self::create(&cert_path, &key_path).await
        }
    }

    /// Loads a TLS identity by reading PEM files from the given paths.
    ///
    /// Both files are read in their entirety into memory. No validation of the certificate
    /// or key contents is performed at this stage; errors will surface later when the
    /// identity is used to configure the TLS acceptor.
    ///
    /// # Errors
    ///
    /// Returns [`super::Error::Io`] if either file cannot be read.
    pub async fn load<P>(cert_path: P, key_path: P) -> Result<Self>
    where
        P: AsRef<Path>,
    {
        let cert_pem = fs::read_to_string(cert_path.as_ref()).await?;
        let key_pem = fs::read_to_string(key_path.as_ref()).await?;

        Ok(Self { cert_pem, key_pem })
    }

    /// Generates a fresh self-signed identity and writes the PEM files to disk.
    async fn create<P>(cert_path: P, key_path: P) -> Result<Self>
    where
        P: AsRef<Path>,
    {
        let identity = Self::forge()?;

        fs::write(cert_path, &identity.cert_pem).await?;
        fs::write(key_path, &identity.key_pem).await?;

        Ok(identity)
    }

    /// Generates a new self-signed certificate in memory without writing to disk.
    fn forge() -> Result<Self> {
        let subject_alt_name = [
            "localhost".to_string(),
            "127.0.0.1".to_string(),
            "0.0.0.0".to_string(),
        ];

        let certified_key = generate_simple_self_signed(&subject_alt_name)?;

        Ok(Self {
            cert_pem: certified_key.cert.pem(),
            key_pem: certified_key.signing_key.serialize_pem(),
        })
    }

    /// Computes the SHA-256 fingerprint of the certificate and returns it as a hex string.
    ///
    /// The fingerprint is computed over the DER-encoded form of the certificate, which is
    /// the standard representation used when displaying fingerprints for manual verification
    /// (e.g., in browser certificate dialogs).
    ///
    /// # Errors
    ///
    /// Returns [`super::Error::Io`] if the PEM data does not contain a valid DER certificate block.
    pub fn fingerprint(&self) -> Result<String> {
        let mut reader = Cursor::new(self.cert_pem.as_bytes());
        let mut cert_iter = certs(&mut reader);

        let der = cert_iter.next().ok_or_else(|| {
            Error::new(
                io::ErrorKind::InvalidData,
                "No certificate found in PEM",
            )
        })??;

        let mut hasher = Sha256::new();
        hasher.update(der.as_ref());
        let result = hasher.finalize();

        let hex_array: Vec<String> =
            result.iter().map(|b| format!("{b:02x}")).collect();
        Ok(hex_array.join(""))
    }

    /// Computes the raw 32-byte SHA-256 fingerprint of the certificate.
    ///
    /// Returns the fingerprint as a fixed-size byte array rather than a hex string.
    /// This form is used by the admin CLI to derive the BIP-39 verification mnemonic
    /// and to encode the certificate fingerprint into a QR code for TOFU device pairing.
    ///
    /// # Errors
    ///
    /// Returns [`super::Error::NoCertificatesFound`] if the PEM data does not contain a valid
    /// DER certificate block. Returns [`super::Error::Io`] if the DER block cannot be parsed.
    pub fn fingerprint_raw(&self) -> Result<[u8; 32]> {
        let mut reader = Cursor::new(self.cert_pem.as_bytes());
        let mut cert_iter = rustls_pemfile::certs(&mut reader);

        let der = cert_iter.next().ok_or(NoCertificatesFound)??;

        let mut hasher = Sha256::new();
        hasher.update(der.as_ref());

        Ok(hasher.finalize().into())
    }
}
