//! TLS identity management for the Kosh server.
//!
//! This module handles the full lifecycle of the server's self-signed TLS certificate:
//!
//! - **Generation** — on first boot, a self-signed X.509 certificate is generated by
//!   [`rcgen`] and written to `<vault_path>/tls/`. Subject Alternative Names cover
//!   `localhost`, `127.0.0.1`, and `0.0.0.0` for LAN deployments.
//! - **Loading** — on subsequent boots, the existing `cert.pem` and `key.pem` files are
//!   read back from disk.
//! - **Fingerprinting** — the SHA-256 fingerprint of the certificate's DER encoding is
//!   made available in two forms:
//!   - A hex string for display purposes.
//!   - A raw `[u8; 32]` for use by the admin CLI to derive the BIP-39 verification
//!     mnemonic and to encode the pairing QR code.
//!
//! The certificate is used both by the Axum HTTP server (via `axum_server` / `rustls`)
//! and by the Android client, which pins it on first connection (Trust-On-First-Use).

mod cert;
mod error;

pub use cert::Identity;

pub use error::{Error, Result};
