use std::num::TryFromIntError;
use std::time::SystemTimeError;

use axum::response::IntoResponse;
use hyper::StatusCode;

use crate::api;
use crate::logger::{Entry, Level, Loggable, logging_enabled};
use crate::storage;
use crate::{model, wrap_internal_err};

pub mod internal;

/// The top-level application error.
///
/// This is the single error type returned by all route handlers via `crate::Result<T>`.
/// It acts as the central hub that aggregates errors from every domain in the application
/// (API layer, storage layer, model layer) through `From` implementations generated by `thiserror`.
///
/// ## How errors flow
///
/// When a route handler uses the `?` operator, errors bubble up through the following chain:
///
/// ```text
/// model::Error  ──┐
/// storage::Error ──┼──► Error ──► IntoResponse (sanitized HTTP response)
/// api::Error   ───┘
/// ```
///
/// The `IntoResponse` implementation here is the **single point of truth** for what the
/// HTTP client is allowed to see. It logs the full internal error (for the server admin)
/// and then delegates to each domain's own `IntoResponse` to produce a sanitized response.
#[derive(thiserror::Error, Debug)]
pub enum Error {
    /// A storage layer error, typically a filesystem or CAS transaction failure.
    #[error(transparent)]
    StorageError(#[from] storage::Error),

    /// An API layer error, typically a bad request or auth failure from a route handler.
    #[error("API Error : {}", .0)]
    ApiError(#[from] api::Error),

    /// A conflict at the application level, such as a duplicate user registration.
    /// This is distinct from a database uniqueness error — it is raised intentionally
    /// by business logic in route handlers.
    #[error("User Conflict")]
    Conflict(String),

    /// A raw database error that was not caught and converted by the model layer.
    /// In practice this should be rare, as most DB queries go through `model::Error`.
    #[error("Database Error : {}", .0)]
    DatabaseError(#[from] sqlx::Error),

    /// A low-level internal error, typically from integer or time conversions.
    #[error("Internal Error : {}", .0)]
    InternalError(#[from] internal::Error),

    /// A model layer error, covering database query results and domain-specific failures
    /// (e.g., asset not found, uniqueness violations).
    #[error("Model Error : {}", .0)]
    ModelError(#[from] model::Error),
}

wrap_internal_err! {
    TryFromIntError, SystemTimeError => Error::InternalError
}

impl IntoResponse for Error {
    fn into_response(self) -> axum::response::Response {
        let telemetry = if logging_enabled() {
            Some(Entry {
                module: self.log_module(),
                level: self.log_level(),
                message: self.to_string(),
                timestamp_ms: chrono::Utc::now().timestamp_millis(),
            })
        } else {
            None
        };

        let mut response = match self {
            // Delegate to each domain's IntoResponse implementation.
            // They know how to sanitize their own errors.
            StorageError(e) => e.into_response(),
            ApiError(e) => e.into_response(),
            ModelError(e) => e.into_response(),

            // Top-level variants that don't belong to a sub-domain.
            Conflict(msg) => (StatusCode::CONFLICT, msg).into_response(),

            // These are always sensitive — never expose details to the client.
            DatabaseError(_) | InternalError(_) => {
                (StatusCode::INTERNAL_SERVER_ERROR, "Internal Server Error")
                    .into_response()
            }
        };

        if let Some(t) = telemetry {
            response.extensions_mut().insert(t);
        }
        response
    }
}

use Error::{
    ApiError, Conflict, DatabaseError, InternalError, ModelError, StorageError,
};

pub type Result<T> = core::result::Result<T, Error>;

impl Loggable for Error {
    fn log_level(&self) -> crate::logger::Level {
        match self {
            Error::StorageError(e) => e.log_level(),
            Error::ApiError(e) => e.log_level(),
            Error::Conflict(_) => Level::Warning,
            Error::ModelError(e) => e.log_level(),
            Error::DatabaseError(_) | Error::InternalError(_) => Level::Error,
        }
    }

    #[inline]
    fn log_module(&self) -> crate::logger::Module {
        match self {
            Error::StorageError(e) => e.log_module(),
            Error::ApiError(e) => e.log_module(),
            Error::ModelError(e) => e.log_module(),
            _ => crate::logger::Module::Server,
        }
    }
}
