use crate::error::Result;
use crate::logger::Module;
use crate::model::session::Session;
use crate::model::user::User;
use crate::{
    api::Error::{BadRequest, Unauthorized},
    app::State as AppState,
};
use crate::{info, warn};
use axum::Json;
use axum::extract::State;
use serde::{Deserialize, Serialize};

/// The JSON body returned on a successful login.
#[derive(Debug, Serialize)]
pub struct LoginResponse {
    /// The raw opaque session token.
    ///
    /// This is a UUID v4 string generated by the server. The client stores it
    /// and passes it as `Authorization: Bearer <token>` on every subsequent request.
    pub token: String,
}

/// The JSON body expected by the login endpoint.
#[derive(Deserialize)]
pub struct LoginRequest {
    /// A hex-encoded BLAKE3 hash of the user's public identity.
    identity_hash: String,
    /// The authentication verifier derived from the user's credentials on the client side.
    auth_verifier: String,
}

/// Authenticates a user and generates a new session token.
///
/// This endpoint verifies the provided identity hash and auth verifier against
/// the database. If successful, it creates a new session and returns the token.
///
/// # Errors
/// - Returns a `BadRequest` if the identity hash cannot be decoded from hex.
/// - Returns an `Unauthorized` if the credentials do not match any existing user.
/// - Returns an internal error if a database query fails.
pub async fn login(
    State(state): State<AppState>,
    Json(request): Json<LoginRequest>,
) -> Result<Json<LoginResponse>> {
    let Ok(identity_hash) = hex::decode(&request.identity_hash) else {
        Err(BadRequest("identity_hash failed to decode".into()))?
    };

    let user_id = User::verify(&state.db, identity_hash, request.auth_verifier)
        .await?
        .ok_or_else(|| {
            warn!(
                Module::Api,
                "Failed login attempt with id : ''",
                // hex::encode(identity_hash)
            );
            Unauthorized("Invalid Credentials".into())
        })?;

    let token = Session::create(&state.db, user_id).await?;

    info!(Module::Api, "User {user_id} successfully logged in");
    Ok(Json(LoginResponse { token }))
}
